/* GENERATED by test/test_gen_jinja.py -- do not edit.
 * Expected values come from real Jinja2; regenerate
 * rather than hand-editing. */
#include "jinja.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

enum { J_OBJ=1, J_ARR, J_STR, J_NUM, J_BOOL };
typedef struct JN {
    int kind; const char *str; long num; int bln;
    const char **keys; const struct JN **vals;
    const struct JN **elems; int n;
} JN;
static struct jinja_value jvk(enum jinja_value_kind k){struct jinja_value v={0};v.kind=k;return v;}
static struct jinja_value wrap(const JN*j){struct jinja_value v={0};
    if(!j)return jvk(JV_UNDEFINED);
    if(j->kind==J_STR){v.kind=JV_STR;v.s=j->str;}
    else if(j->kind==J_NUM){v.kind=JV_INT;v.i=j->num;}
    else if(j->kind==J_BOOL){v.kind=JV_BOOL;v.i=j->bln;}
    else{v.kind=JV_NODE;v.tag=j->kind;v.node=j;v.i=j->n;}return v;}
static struct jinja_value g(void*c,struct jinja_value o,const char*n){(void)c;
    if(o.kind==JV_NODE&&o.tag==J_OBJ){const JN*j=o.node;
        for(int i=0;i<j->n;i++)if(!strcmp(j->keys[i],n))return wrap(j->vals[i]);}
    return jvk(JV_UNDEFINED);}
static struct jinja_value ix(void*c,struct jinja_value o,long i){(void)c;
    if(o.kind!=JV_NODE)return jvk(JV_UNDEFINED);
    const JN*j=o.node;
    if(j->kind==J_OBJ){struct jinja_value v={0};v.kind=JV_STR;v.s=j->keys[i];return v;}
    if(j->kind==J_ARR)return wrap(j->elems[i]);
    return jvk(JV_UNDEFINED);}
static long ln(void*c,struct jinja_value o){(void)c;return o.kind==JV_NODE?((const JN*)o.node)->n:0;}
static int tr(void*c,struct jinja_value v){(void)c;return v.kind==JV_NODE?((const JN*)v.node)->n!=0:0;}
static int ts(void*c,struct jinja_value v,const char*n){(void)c;
    if(v.kind!=JV_NODE)return 0;
    int k=((const JN*)v.node)->kind;
    if(!strcmp(n,"mapping"))return k==J_OBJ;
    if(!strcmp(n,"sequence")||!strcmp(n,"iterable"))return k==J_ARR;
    return 0;}
static struct jinja_value mt(void*c,struct jinja_value o,const char*n,struct jinja_value a){
    (void)c;(void)o;(void)n;(void)a;return jvk(JV_UNDEFINED);}
static struct jinja_host H={g,ix,ln,tr,ts,mt,0};
static int fails;
static void ck(const char*nm,const char*t,const char*w,struct jinja_var*v,int nv){
    char*o=jinja_render(t,&H,v,nv);
    int ok=o&&!strcmp(o,w);
    printf("%-20s %s\n",nm,ok?"PASS":"FAIL");
    if(!ok){fails++;printf("    want=[%s]\n    got =[%s]\n",w,o?o:"(null)");}
    free(o);}
static const JN jn1={J_NUM,0,1,0,0,0,0,0};
static const JN jn2={J_NUM,0,2,0,0,0,0,0};
static const JN jn3={J_NUM,0,3,0,0,0,0,0};
static const JN* jn0_e[]={&jn1,&jn2,&jn3};
static const JN jn0={J_ARR,0,0,0,0,0,jn0_e,3};
static const JN jn5={J_NUM,0,1,0,0,0,0,0};
static const JN jn6={J_NUM,0,2,0,0,0,0,0};
static const JN jn7={J_NUM,0,3,0,0,0,0,0};
static const JN* jn4_e[]={&jn5,&jn6,&jn7};
static const JN jn4={J_ARR,0,0,0,0,0,jn4_e,3};
static const JN jn9={J_NUM,0,3,0,0,0,0,0};
static const JN jn10={J_NUM,0,1,0,0,0,0,0};
static const JN jn11={J_NUM,0,2,0,0,0,0,0};
static const JN* jn8_e[]={&jn9,&jn10,&jn11};
static const JN jn8={J_ARR,0,0,0,0,0,jn8_e,3};
static const JN jn13={J_NUM,0,3,0,0,0,0,0};
static const JN jn14={J_NUM,0,1,0,0,0,0,0};
static const JN jn15={J_NUM,0,2,0,0,0,0,0};
static const JN* jn12_e[]={&jn13,&jn14,&jn15};
static const JN jn12={J_ARR,0,0,0,0,0,jn12_e,3};
static const JN jn18={J_STR,"a",0,0,0,0,0,0};
static const JN jn19={J_NUM,0,30,0,0,0,0,0};
static const char* jn17_k[]={"name","age"};
static const JN* jn17_v[]={&jn18,&jn19};
static const JN jn17={J_OBJ,0,0,0,jn17_k,jn17_v,0,2};
static const JN jn21={J_STR,"b",0,0,0,0,0,0};
static const JN jn22={J_NUM,0,20,0,0,0,0,0};
static const char* jn20_k[]={"name","age"};
static const JN* jn20_v[]={&jn21,&jn22};
static const JN jn20={J_OBJ,0,0,0,jn20_k,jn20_v,0,2};
static const JN* jn16_e[]={&jn17,&jn20};
static const JN jn16={J_ARR,0,0,0,0,0,jn16_e,2};
static const JN jn24={J_NUM,0,1,0,0,0,0,0};
static const JN jn25={J_NUM,0,1,0,0,0,0,0};
static const JN jn26={J_NUM,0,2,0,0,0,0,0};
static const JN jn27={J_NUM,0,3,0,0,0,0,0};
static const JN jn28={J_NUM,0,3,0,0,0,0,0};
static const JN* jn23_e[]={&jn24,&jn25,&jn26,&jn27,&jn28};
static const JN jn23={J_ARR,0,0,0,0,0,jn23_e,5};
static const JN jn30={J_NUM,0,3,0,0,0,0,0};
static const JN jn31={J_NUM,0,1,0,0,0,0,0};
static const JN jn32={J_NUM,0,2,0,0,0,0,0};
static const JN* jn29_e[]={&jn30,&jn31,&jn32};
static const JN jn29={J_ARR,0,0,0,0,0,jn29_e,3};
static const JN jn34={J_NUM,0,1,0,0,0,0,0};
static const JN jn35={J_NUM,0,2,0,0,0,0,0};
static const JN jn36={J_NUM,0,3,0,0,0,0,0};
static const JN* jn33_e[]={&jn34,&jn35,&jn36};
static const JN jn33={J_ARR,0,0,0,0,0,jn33_e,3};
static const JN jn37={J_NUM,0,-5,0,0,0,0,0};
static const JN jn38={J_STR,"hello world",0,0,0,0,0,0};
static const JN jn40={J_NUM,0,0,0,0,0,0,0};
static const JN jn41={J_NUM,0,1,0,0,0,0,0};
static const JN jn42={J_NUM,0,2,0,0,0,0,0};
static const JN jn43={J_NUM,0,0,0,0,0,0,0};
static const JN jn44={J_NUM,0,3,0,0,0,0,0};
static const JN* jn39_e[]={&jn40,&jn41,&jn42,&jn43,&jn44};
static const JN jn39={J_ARR,0,0,0,0,0,jn39_e,5};
static const JN jn46={J_NUM,0,0,0,0,0,0,0};
static const JN jn47={J_NUM,0,1,0,0,0,0,0};
static const JN jn48={J_NUM,0,2,0,0,0,0,0};
static const JN jn49={J_NUM,0,0,0,0,0,0,0};
static const JN jn50={J_NUM,0,3,0,0,0,0,0};
static const JN* jn45_e[]={&jn46,&jn47,&jn48,&jn49,&jn50};
static const JN jn45={J_ARR,0,0,0,0,0,jn45_e,5};
static const JN jn53={J_STR,"a",0,0,0,0,0,0};
static const JN jn54={J_BOOL,0,0,1,0,0,0,0};
static const char* jn52_k[]={"name","active"};
static const JN* jn52_v[]={&jn53,&jn54};
static const JN jn52={J_OBJ,0,0,0,jn52_k,jn52_v,0,2};
static const JN jn56={J_STR,"b",0,0,0,0,0,0};
static const JN jn57={J_BOOL,0,0,0,0,0,0,0};
static const char* jn55_k[]={"name","active"};
static const JN* jn55_v[]={&jn56,&jn57};
static const JN jn55={J_OBJ,0,0,0,jn55_k,jn55_v,0,2};
static const JN* jn51_e[]={&jn52,&jn55};
static const JN jn51={J_ARR,0,0,0,0,0,jn51_e,2};
static const JN jn60={J_STR,"a",0,0,0,0,0,0};
static const JN jn61={J_BOOL,0,0,1,0,0,0,0};
static const char* jn59_k[]={"name","active"};
static const JN* jn59_v[]={&jn60,&jn61};
static const JN jn59={J_OBJ,0,0,0,jn59_k,jn59_v,0,2};
static const JN jn63={J_STR,"b",0,0,0,0,0,0};
static const JN jn64={J_BOOL,0,0,0,0,0,0,0};
static const char* jn62_k[]={"name","active"};
static const JN* jn62_v[]={&jn63,&jn64};
static const JN jn62={J_OBJ,0,0,0,jn62_k,jn62_v,0,2};
static const JN* jn58_e[]={&jn59,&jn62};
static const JN jn58={J_ARR,0,0,0,0,0,jn58_e,2};
static const JN jn66={J_STR,"a",0,0,0,0,0,0};
static const JN jn67={J_STR,"b",0,0,0,0,0,0};
static const JN* jn65_e[]={&jn66,&jn67};
static const JN jn65={J_ARR,0,0,0,0,0,jn65_e,2};
static const JN jn70={J_STR,"a",0,0,0,0,0,0};
static const char* jn69_k[]={"name"};
static const JN* jn69_v[]={&jn70};
static const JN jn69={J_OBJ,0,0,0,jn69_k,jn69_v,0,1};
static const JN jn72={J_STR,"b",0,0,0,0,0,0};
static const char* jn71_k[]={"name"};
static const JN* jn71_v[]={&jn72};
static const JN jn71={J_OBJ,0,0,0,jn71_k,jn71_v,0,1};
static const JN* jn68_e[]={&jn69,&jn71};
static const JN jn68={J_ARR,0,0,0,0,0,jn68_e,2};
static const JN jn75={J_STR,"x",0,0,0,0,0,0};
static const JN jn76={J_STR,"a",0,0,0,0,0,0};
static const char* jn74_k[]={"cat","name"};
static const JN* jn74_v[]={&jn75,&jn76};
static const JN jn74={J_OBJ,0,0,0,jn74_k,jn74_v,0,2};
static const JN jn78={J_STR,"y",0,0,0,0,0,0};
static const JN jn79={J_STR,"b",0,0,0,0,0,0};
static const char* jn77_k[]={"cat","name"};
static const JN* jn77_v[]={&jn78,&jn79};
static const JN jn77={J_OBJ,0,0,0,jn77_k,jn77_v,0,2};
static const JN jn81={J_STR,"x",0,0,0,0,0,0};
static const JN jn82={J_STR,"c",0,0,0,0,0,0};
static const char* jn80_k[]={"cat","name"};
static const JN* jn80_v[]={&jn81,&jn82};
static const JN jn80={J_OBJ,0,0,0,jn80_k,jn80_v,0,2};
static const JN* jn73_e[]={&jn74,&jn77,&jn80};
static const JN jn73={J_ARR,0,0,0,0,0,jn73_e,3};
static const JN jn84={J_NUM,0,2,0,0,0,0,0};
static const JN jn85={J_NUM,0,1,0,0,0,0,0};
static const char* jn83_k[]={"b","a"};
static const JN* jn83_v[]={&jn84,&jn85};
static const JN jn83={J_OBJ,0,0,0,jn83_k,jn83_v,0,2};
static const JN jn87={J_NUM,0,1,0,0,0,0,0};
static const JN jn88={J_NUM,0,2,0,0,0,0,0};
static const JN jn89={J_NUM,0,3,0,0,0,0,0};
static const JN* jn86_e[]={&jn87,&jn88,&jn89};
static const JN jn86={J_ARR,0,0,0,0,0,jn86_e,3};
static const JN jn90={J_NUM,0,3,0,0,0,0,0};
static const JN jn91={J_STR,"a",0,0,0,0,0,0};
static const JN jn92={J_NUM,0,3,0,0,0,0,0};
static const JN jn93={J_STR,"a",0,0,0,0,0,0};
static const JN jn95={J_NUM,0,1,0,0,0,0,0};
static const char* jn94_k[]={"a"};
static const JN* jn94_v[]={&jn95};
static const JN jn94={J_OBJ,0,0,0,jn94_k,jn94_v,0,1};
static const JN jn97={J_NUM,0,1,0,0,0,0,0};
static const JN* jn96_e[]={&jn97};
static const JN jn96={J_ARR,0,0,0,0,0,jn96_e,1};
static const JN jn99={J_NUM,0,1,0,0,0,0,0};
static const JN* jn98_e[]={&jn99};
static const JN jn98={J_ARR,0,0,0,0,0,jn98_e,1};
static const JN jn100={J_NUM,0,3,0,0,0,0,0};
static const JN jn102={J_NUM,0,1,0,0,0,0,0};
static const JN jn103={J_NUM,0,2,0,0,0,0,0};
static const JN jn104={J_NUM,0,3,0,0,0,0,0};
static const JN jn105={J_NUM,0,4,0,0,0,0,0};
static const JN* jn101_e[]={&jn102,&jn103,&jn104,&jn105};
static const JN jn101={J_ARR,0,0,0,0,0,jn101_e,4};
static const JN jn107={J_NUM,0,1,0,0,0,0,0};
static const JN jn108={J_NUM,0,2,0,0,0,0,0};
static const JN jn109={J_NUM,0,3,0,0,0,0,0};
static const JN jn110={J_NUM,0,4,0,0,0,0,0};
static const JN* jn106_e[]={&jn107,&jn108,&jn109,&jn110};
static const JN jn106={J_ARR,0,0,0,0,0,jn106_e,4};
static const JN jn112={J_NUM,0,1,0,0,0,0,0};
static const JN jn113={J_NUM,0,2,0,0,0,0,0};
static const JN jn114={J_NUM,0,3,0,0,0,0,0};
static const JN jn115={J_NUM,0,4,0,0,0,0,0};
static const JN* jn111_e[]={&jn112,&jn113,&jn114,&jn115};
static const JN jn111={J_ARR,0,0,0,0,0,jn111_e,4};
static const JN jn117={J_NUM,0,1,0,0,0,0,0};
static const JN jn118={J_NUM,0,2,0,0,0,0,0};
static const JN jn119={J_NUM,0,3,0,0,0,0,0};
static const JN jn120={J_NUM,0,4,0,0,0,0,0};
static const JN* jn116_e[]={&jn117,&jn118,&jn119,&jn120};
static const JN jn116={J_ARR,0,0,0,0,0,jn116_e,4};
static const JN jn122={J_NUM,0,1,0,0,0,0,0};
static const JN jn123={J_NUM,0,2,0,0,0,0,0};
static const JN jn124={J_NUM,0,3,0,0,0,0,0};
static const JN jn125={J_NUM,0,4,0,0,0,0,0};
static const JN* jn121_e[]={&jn122,&jn123,&jn124,&jn125};
static const JN jn121={J_ARR,0,0,0,0,0,jn121_e,4};
static const JN jn127={J_NUM,0,1,0,0,0,0,0};
static const JN jn128={J_NUM,0,2,0,0,0,0,0};
static const JN jn129={J_NUM,0,3,0,0,0,0,0};
static const JN jn130={J_NUM,0,4,0,0,0,0,0};
static const JN* jn126_e[]={&jn127,&jn128,&jn129,&jn130};
static const JN jn126={J_ARR,0,0,0,0,0,jn126_e,4};
static const JN jn132={J_NUM,0,1,0,0,0,0,0};
static const JN jn133={J_NUM,0,2,0,0,0,0,0};
static const JN jn134={J_NUM,0,3,0,0,0,0,0};
static const JN jn135={J_NUM,0,4,0,0,0,0,0};
static const JN* jn131_e[]={&jn132,&jn133,&jn134,&jn135};
static const JN jn131={J_ARR,0,0,0,0,0,jn131_e,4};
static const JN jn137={J_NUM,0,1,0,0,0,0,0};
static const JN jn138={J_NUM,0,2,0,0,0,0,0};
static const JN jn139={J_NUM,0,3,0,0,0,0,0};
static const JN jn140={J_NUM,0,4,0,0,0,0,0};
static const JN* jn136_e[]={&jn137,&jn138,&jn139,&jn140};
static const JN jn136={J_ARR,0,0,0,0,0,jn136_e,4};
static const JN jn142={J_NUM,0,1,0,0,0,0,0};
static const JN jn143={J_NUM,0,2,0,0,0,0,0};
static const JN jn144={J_NUM,0,3,0,0,0,0,0};
static const JN jn145={J_NUM,0,4,0,0,0,0,0};
static const JN* jn141_e[]={&jn142,&jn143,&jn144,&jn145};
static const JN jn141={J_ARR,0,0,0,0,0,jn141_e,4};
static const JN jn146={J_BOOL,0,0,1,0,0,0,0};
static const JN jn147={J_BOOL,0,0,0,0,0,0,0};
static const JN jn148={J_STR,"",0,0,0,0,0,0};
static const JN jn149={J_STR,"y",0,0,0,0,0,0};
static const JN jn150={J_ARR,0,0,0,0,0,0,0};
static const JN jn152={J_NUM,0,1,0,0,0,0,0};
static const JN jn153={J_NUM,0,2,0,0,0,0,0};
static const JN* jn151_e[]={&jn152,&jn153};
static const JN jn151={J_ARR,0,0,0,0,0,jn151_e,2};
static const JN jn155={J_NUM,0,1,0,0,0,0,0};
static const JN jn156={J_NUM,0,2,0,0,0,0,0};
static const JN* jn154_e[]={&jn155,&jn156};
static const JN jn154={J_ARR,0,0,0,0,0,jn154_e,2};
static const JN jn158={J_NUM,0,9,0,0,0,0,0};
static const JN* jn157_e[]={&jn158};
static const JN jn157={J_ARR,0,0,0,0,0,jn157_e,1};
static const JN jn160={J_NUM,0,0,0,0,0,0,0};
static const JN jn161={J_NUM,0,1,0,0,0,0,0};
static const JN jn162={J_NUM,0,2,0,0,0,0,0};
static const JN jn163={J_NUM,0,3,0,0,0,0,0};
static const JN* jn159_e[]={&jn160,&jn161,&jn162,&jn163};
static const JN jn159={J_ARR,0,0,0,0,0,jn159_e,4};
static const JN jn165={J_NUM,0,0,0,0,0,0,0};
static const JN jn166={J_NUM,0,1,0,0,0,0,0};
static const JN jn167={J_NUM,0,2,0,0,0,0,0};
static const JN jn168={J_NUM,0,3,0,0,0,0,0};
static const JN* jn164_e[]={&jn165,&jn166,&jn167,&jn168};
static const JN jn164={J_ARR,0,0,0,0,0,jn164_e,4};
static const JN jn171={J_STR,"sys",0,0,0,0,0,0};
static const char* jn170_k[]={"role"};
static const JN* jn170_v[]={&jn171};
static const JN jn170={J_OBJ,0,0,0,jn170_k,jn170_v,0,1};
static const JN jn173={J_STR,"usr",0,0,0,0,0,0};
static const char* jn172_k[]={"role"};
static const JN* jn172_v[]={&jn173};
static const JN jn172={J_OBJ,0,0,0,jn172_k,jn172_v,0,1};
static const JN jn175={J_STR,"sys",0,0,0,0,0,0};
static const char* jn174_k[]={"role"};
static const JN* jn174_v[]={&jn175};
static const JN jn174={J_OBJ,0,0,0,jn174_k,jn174_v,0,1};
static const JN* jn169_e[]={&jn170,&jn172,&jn174};
static const JN jn169={J_ARR,0,0,0,0,0,jn169_e,3};
static const JN jn178={J_STR,"sys",0,0,0,0,0,0};
static const char* jn177_k[]={"role"};
static const JN* jn177_v[]={&jn178};
static const JN jn177={J_OBJ,0,0,0,jn177_k,jn177_v,0,1};
static const JN jn180={J_STR,"usr",0,0,0,0,0,0};
static const char* jn179_k[]={"role"};
static const JN* jn179_v[]={&jn180};
static const JN jn179={J_OBJ,0,0,0,jn179_k,jn179_v,0,1};
static const JN* jn176_e[]={&jn177,&jn179};
static const JN jn176={J_ARR,0,0,0,0,0,jn176_e,2};
static const JN jn183={J_STR,"a",0,0,0,0,0,0};
static const JN jn184={J_NUM,0,30,0,0,0,0,0};
static const char* jn182_k[]={"name","age"};
static const JN* jn182_v[]={&jn183,&jn184};
static const JN jn182={J_OBJ,0,0,0,jn182_k,jn182_v,0,2};
static const JN jn186={J_STR,"b",0,0,0,0,0,0};
static const JN jn187={J_NUM,0,20,0,0,0,0,0};
static const char* jn185_k[]={"name","age"};
static const JN* jn185_v[]={&jn186,&jn187};
static const JN jn185={J_OBJ,0,0,0,jn185_k,jn185_v,0,2};
static const JN jn189={J_STR,"c",0,0,0,0,0,0};
static const JN jn190={J_NUM,0,40,0,0,0,0,0};
static const char* jn188_k[]={"name","age"};
static const JN* jn188_v[]={&jn189,&jn190};
static const JN jn188={J_OBJ,0,0,0,jn188_k,jn188_v,0,2};
static const JN* jn181_e[]={&jn182,&jn185,&jn188};
static const JN jn181={J_ARR,0,0,0,0,0,jn181_e,3};
static const JN jn193={J_STR,"system",0,0,0,0,0,0};
static const char* jn192_k[]={"role"};
static const JN* jn192_v[]={&jn193};
static const JN jn192={J_OBJ,0,0,0,jn192_k,jn192_v,0,1};
static const JN jn195={J_STR,"user",0,0,0,0,0,0};
static const char* jn194_k[]={"role"};
static const JN* jn194_v[]={&jn195};
static const JN jn194={J_OBJ,0,0,0,jn194_k,jn194_v,0,1};
static const JN* jn191_e[]={&jn192,&jn194};
static const JN jn191={J_ARR,0,0,0,0,0,jn191_e,2};
static const JN jn198={J_STR,"user",0,0,0,0,0,0};
static const char* jn197_k[]={"role"};
static const JN* jn197_v[]={&jn198};
static const JN jn197={J_OBJ,0,0,0,jn197_k,jn197_v,0,1};
static const JN* jn196_e[]={&jn197};
static const JN jn196={J_ARR,0,0,0,0,0,jn196_e,1};
static void t0(void){
    struct jinja_var v[]={{"items",wrap(&jn0)}};
    ck("count","{{ items|count }}","3",v,1);
}
static void t1(void){
    struct jinja_var v[]={{"items",wrap(&jn4)}};
    ck("reverse","{{ items|reverse|join(',') }}","3,2,1",v,1);
}
static void t2(void){
    struct jinja_var v[]={{"nums",wrap(&jn8)}};
    ck("sort","{{ nums|sort|join(',') }}","1,2,3",v,1);
}
static void t3(void){
    struct jinja_var v[]={{"nums",wrap(&jn12)}};
    ck("sort_rev","{{ nums|sort(reverse=true)|join(',') }}","3,2,1",v,1);
}
static void t4(void){
    struct jinja_var v[]={{"people",wrap(&jn16)}};
    ck("sort_attr","{{ people|sort(attribute='age')|map(attribute='name')|join(',') }}","b,a",v,1);
}
static void t5(void){
    struct jinja_var v[]={{"xs",wrap(&jn23)}};
    ck("unique","{{ xs|unique|join(',') }}","1,2,3",v,1);
}
static void t6(void){
    struct jinja_var v[]={{"nums",wrap(&jn29)}};
    ck("min_max","{{ nums|min }}/{{ nums|max }}","1/3",v,1);
}
static void t7(void){
    struct jinja_var v[]={{"nums",wrap(&jn33)}};
    ck("sum","{{ nums|sum }}","6",v,1);
}
static void t8(void){
    struct jinja_var v[]={{"neg",wrap(&jn37)}};
    ck("abs","{{ neg|abs }}","5",v,1);
}
static void t9(void){
    struct jinja_var v[]={{"s",wrap(&jn38)}};
    ck("title","{{ s|title }}","Hello World",v,1);
}
static void t10(void){
    struct jinja_var v[]={{"flags",wrap(&jn39)}};
    ck("select","{{ flags|select|join(',') }}","1,2,3",v,1);
}
static void t11(void){
    struct jinja_var v[]={{"flags",wrap(&jn45)}};
    ck("reject","{{ flags|reject|join(',') }}","0,0",v,1);
}
static void t12(void){
    struct jinja_var v[]={{"people",wrap(&jn51)}};
    ck("selectattr","{{ people|selectattr('active')|map(attribute='name')|join(',') }}","a",v,1);
}
static void t13(void){
    struct jinja_var v[]={{"people",wrap(&jn58)}};
    ck("rejectattr","{{ people|rejectattr('active')|map(attribute='name')|join(',') }}","b",v,1);
}
static void t14(void){
    struct jinja_var v[]={{"words",wrap(&jn65)}};
    ck("map_upper","{{ words|map('upper')|join(',') }}","A,B",v,1);
}
static void t15(void){
    struct jinja_var v[]={{"people",wrap(&jn68)}};
    ck("map_attr","{{ people|map(attribute='name')|join(',') }}","a,b",v,1);
}
static void t16(void){
    struct jinja_var v[]={{"items",wrap(&jn73)}};
    ck("groupby","{% for k, g in items|groupby('cat') -%}{{ k }}:{{ g|map(attribute='name')|join('+') }};{%- endfor %}","x:a+c;y:b;",v,1);
}
static void t17(void){
    struct jinja_var v[]={{"d",wrap(&jn83)}};
    ck("dictsort","{% for k, v in d|dictsort -%}{{ k }}={{ v }};{%- endfor %}","a=1;b=2;",v,1);
}
static void t18(void){
    ck("default_falsy","{{ ''|default('x', true) }}/{{ ''|default('x') }}","x/",0,0);
}
static void t19(void){
    ck("replace","{{ 'a.b'|replace('.', '_') }}","a_b",0,0);
}
static void t20(void){
    ck("capitalize","{{ 'hi there'|capitalize }}","Hi there",0,0);
}
static void t21(void){
    ck("trim","{{ '  hi  '|trim }}","hi",0,0);
}
static void t22(void){
    struct jinja_var v[]={{"nums",wrap(&jn86)}};
    ck("even_odd","{% for n in nums -%}{{ n }}:{{ 'E' if n is even else 'O' }};{%- endfor %}","1:O;2:E;3:O;",v,1);
}
static void t23(void){
    struct jinja_var v[]={{"x",wrap(&jn90)},{"s",wrap(&jn91)}};
    ck("is_number","{{ x is number }}/{{ s is number }}","True/False",v,2);
}
static void t24(void){
    struct jinja_var v[]={{"x",wrap(&jn92)},{"s",wrap(&jn93)}};
    ck("is_string","{{ s is string }}/{{ x is string }}","True/False",v,2);
}
static void t25(void){
    struct jinja_var v[]={{"d",wrap(&jn94)},{"xs",wrap(&jn96)}};
    ck("is_mapping","{{ d is mapping }}/{{ xs is mapping }}","True/False",v,2);
}
static void t26(void){
    struct jinja_var v[]={{"xs",wrap(&jn98)},{"x",wrap(&jn100)}};
    ck("is_seq","{{ xs is sequence }}/{{ x is sequence }}","True/False",v,2);
}
static void t27(void){
    struct jinja_var v[]={{"xs",wrap(&jn101)}};
    ck("slice_from","{{ xs[1:]|join(',') }}","2,3,4",v,1);
}
static void t28(void){
    struct jinja_var v[]={{"xs",wrap(&jn106)}};
    ck("slice_to","{{ xs[:2]|join(',') }}","1,2",v,1);
}
static void t29(void){
    struct jinja_var v[]={{"xs",wrap(&jn111)}};
    ck("slice_mid","{{ xs[1:3]|join(',') }}","2,3",v,1);
}
static void t30(void){
    struct jinja_var v[]={{"xs",wrap(&jn116)}};
    ck("slice_rev","{{ xs[::-1]|join(',') }}","4,3,2,1",v,1);
}
static void t31(void){
    struct jinja_var v[]={{"xs",wrap(&jn121)}};
    ck("slice_step","{{ xs[::2]|join(',') }}","1,3",v,1);
}
static void t32(void){
    struct jinja_var v[]={{"xs",wrap(&jn126)}};
    ck("slice_negstart","{{ xs[-2:]|join(',') }}","3,4",v,1);
}
static void t33(void){
    struct jinja_var v[]={{"xs",wrap(&jn131)}};
    ck("slice_negstop","{{ xs[:-1]|join(',') }}","1,2,3",v,1);
}
static void t34(void){
    struct jinja_var v[]={{"xs",wrap(&jn136)}};
    ck("slice_full","{{ xs[1:4:2]|join(',') }}","2,4",v,1);
}
static void t35(void){
    struct jinja_var v[]={{"xs",wrap(&jn141)}};
    ck("slice_revstep","{{ xs[3:0:-1]|join(',') }}","4,3,2",v,1);
}
static void t36(void){
    ck("dict_literal","{{ {'a': 1, 'b': 2}|length }}","2",0,0);
}
static void t37(void){
    ck("dict_literal_sort","{% for k, v in {'b': 2, 'a': 1}|dictsort -%}{{ k }}{{ v }}{%- endfor %}","a1b2",0,0);
}
static void t38(void){
    struct jinja_var v[]={{"cond",wrap(&jn146)}};
    ck("inline_if_true","{{ 'yes' if cond }}","yes",v,1);
}
static void t39(void){
    struct jinja_var v[]={{"cond",wrap(&jn147)}};
    ck("inline_if_false","[{{ 'yes' if cond }}]","[]",v,1);
}
static void t40(void){
    ck("list_literal","{{ [1, 2, 3]|join('-') }}","1-2-3",0,0);
}
static void t41(void){
    struct jinja_var v[]={{"a",wrap(&jn148)}};
    ck("or_value","{{ a or 'def' }}","def",v,1);
}
static void t42(void){
    struct jinja_var v[]={{"a",wrap(&jn149)}};
    ck("and_value","{{ a and 'x' }}","x",v,1);
}
static void t43(void){
    ck("range1","{{ range(3)|join(',') }}","0,1,2",0,0);
}
static void t44(void){
    ck("range2","{{ range(2, 5)|join(',') }}","2,3,4",0,0);
}
static void t45(void){
    ck("range3","{{ range(0, 10, 3)|join(',') }}","0,3,6,9",0,0);
}
static void t46(void){
    ck("set_block","{%- set x %}hi{% endset -%}[{{ x }}]","[hi]",0,0);
}
static void t47(void){
    ck("filter_block","{%- filter upper -%}hi there{%- endfilter -%}","HI THERE",0,0);
}
static void t48(void){
    struct jinja_var v[]={{"xs",wrap(&jn150)}};
    ck("for_else_empty","{%- for i in xs -%}{{ i }}{%- else -%}none{%- endfor -%}","none",v,1);
}
static void t49(void){
    struct jinja_var v[]={{"xs",wrap(&jn151)}};
    ck("for_else_full","{%- for i in xs -%}{{ i }}{%- else -%}none{%- endfor -%}","12",v,1);
}
static void t50(void){
    struct jinja_var v[]={{"outer",wrap(&jn154)},{"inner",wrap(&jn157)}};
    ck("nested_loop_scope","{%- for a in outer -%}{%- for b in inner -%}{%- endfor -%}{{ loop.index }};{%- endfor -%}","1;2;",v,2);
}
static void t51(void){
    ck("kwargs","{%- macro f(a, b=2) -%}{{ a }}-{{ b }}{%- endmacro -%}{{ f(1) }}|{{ f(1, b=9) }}","1-2|1-9",0,0);
}
static void t52(void){
    ck("mul","{{ 6 * 7 }}","42",0,0);
}
static void t53(void){
    ck("mod","{{ 7 % 3 }}","1",0,0);
}
static void t54(void){
    ck("mod_neg","{{ -7 % 3 }}","2",0,0);
}
static void t55(void){
    ck("floordiv","{{ 7 // 2 }}","3",0,0);
}
static void t56(void){
    ck("floordiv_neg","{{ -7 // 2 }}","-4",0,0);
}
static void t57(void){
    ck("pow","{{ 2 ** 10 }}","1024",0,0);
}
static void t58(void){
    ck("pow_unary","{{ -2 ** 2 }}","4",0,0);
}
static void t59(void){
    ck("prec_muladd","{{ 2 + 3 * 4 }}","14",0,0);
}
static void t60(void){
    ck("prec_parens","{{ (2 + 3) * 4 }}","20",0,0);
}
static void t61(void){
    struct jinja_var v[]={{"nums",wrap(&jn159)}};
    ck("mod_role","{%- for n in nums -%}{{ n % 2 }}{%- endfor -%}","0101",v,1);
}
static void t62(void){
    struct jinja_var v[]={{"nums",wrap(&jn164)}};
    ck("mod_in_cmp","{%- for i in nums -%}{{ 'A' if i % 2 == 0 else 'B' }}{%- endfor -%}","ABAB",v,1);
}
static void t63(void){
    ck("dead_filter","{% if False %}{{ x|nofilter }}{% endif %}ok","ok",0,0);
}
static void t64(void){
    ck("dead_test","{% if False %}{{ x is notest }}{% endif %}ok","ok",0,0);
}
static void t65(void){
    ck("dead_function","{% if False %}{{ nofunc() }}{% endif %}ok","ok",0,0);
}
static void t66(void){
    ck("dead_strftime","{% if False %}{{ strftime_now('%Y') }}{% endif %}ok","ok",0,0);
}
static void t67(void){
    ck("eq_str_bool","{{ 'hi' == false }}","False",0,0);
}
static void t68(void){
    ck("eq_emptystr_bool","{{ '' == false }}","False",0,0);
}
static void t69(void){
    ck("eq_int_bool","{{ 0 == false }}/{{ 1 == true }}/{{ 2 == true }}","True/True/False",0,0);
}
static void t70(void){
    ck("eq_str_int","{{ '1' == 1 }}","False",0,0);
}
static void t71(void){
    ck("eq_none_bool","{{ none == false }}/{{ none == none }}","False/True",0,0);
}
static void t72(void){
    ck("ne_str_bool_sentinel","{{ 'hi' != false }}/{{ '' != false }}","True/True",0,0);
}
static void t73(void){
    struct jinja_var v[]={{"people",wrap(&jn169)}};
    ck("selectattr_equalto","{{ people|selectattr('role', 'equalto', 'sys')|list|length }}","2",v,1);
}
static void t74(void){
    struct jinja_var v[]={{"people",wrap(&jn176)}};
    ck("rejectattr_equalto","{{ people|rejectattr('role', 'equalto', 'sys')|map(attribute='role')|join(',') }}","usr",v,1);
}
static void t75(void){
    struct jinja_var v[]={{"people",wrap(&jn181)}};
    ck("selectattr_gt","{{ people|selectattr('age', 'greaterthan', 25)|map(attribute='name')|join(',') }}","a,c",v,1);
}
static void t76(void){
    struct jinja_var v[]={{"messages",wrap(&jn191)}};
    ck("has_system_idiom","{{ messages|selectattr('role', 'equalto', 'system')|list|length > 0 }}","True",v,1);
}
static void t77(void){
    struct jinja_var v[]={{"messages",wrap(&jn196)}};
    ck("has_system_absent","{{ messages|selectattr('role', 'equalto', 'system')|list|length > 0 }}","False",v,1);
}
static void t78(void){
    ck("range_is_defined","{{ range is defined }}","True",0,0);
}
static void t79(void){
    ck("namespace_is_defined","{{ namespace is defined }}","True",0,0);
}
static void t80(void){
    ck("missing_is_defined","{{ nope_xyz is defined }}","False",0,0);
}
static void t81(void){
    ck("missing_is_undefined","{{ nope_xyz is undefined }}","True",0,0);
}
static void t82(void){
    ck("set_var_is_defined","{% set x = 1 %}{{ x is defined }}","True",0,0);
}
int main(void){
    t0();
    t1();
    t2();
    t3();
    t4();
    t5();
    t6();
    t7();
    t8();
    t9();
    t10();
    t11();
    t12();
    t13();
    t14();
    t15();
    t16();
    t17();
    t18();
    t19();
    t20();
    t21();
    t22();
    t23();
    t24();
    t25();
    t26();
    t27();
    t28();
    t29();
    t30();
    t31();
    t32();
    t33();
    t34();
    t35();
    t36();
    t37();
    t38();
    t39();
    t40();
    t41();
    t42();
    t43();
    t44();
    t45();
    t46();
    t47();
    t48();
    t49();
    t50();
    t51();
    t52();
    t53();
    t54();
    t55();
    t56();
    t57();
    t58();
    t59();
    t60();
    t61();
    t62();
    t63();
    t64();
    t65();
    t66();
    t67();
    t68();
    t69();
    t70();
    t71();
    t72();
    t73();
    t74();
    t75();
    t76();
    t77();
    t78();
    t79();
    t80();
    t81();
    t82();
    printf(fails?"\n%d FAILED\n":"\nALL GOLDEN TESTS PASS\n",fails);
    return fails?1:0;}
